name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
inputs:
  flags:
    description: "Additional `codeql test run` flags"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: ./swift/actions/share-extractor-pack
    - uses: ./.github/actions/fetch-codeql
    - id: query-cache
      uses: ./.github/actions/cache-query-compilation
      with:
        key: swift-qltest
    - name: Run QL tests
      shell: bash
      run: |
        codeql test run \
          --threads=0 \
          --ram 52000 \
          --search-path "${{ github.workspace }}/swift/extractor-pack" \
          --check-databases \
          --check-unused-labels \
          --check-repeated-labels \
          --check-redefined-labels \
          --check-use-before-definition \
          --compilation-cache "${{ steps.query-cache.outputs.cache-dir }}" \
          --show-extractor-output \
          ${{ inputs.flags }} \
          /home/runner/work/codeql/codeql/swift/ql/test/extractor-tests/declarations/all.ql
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload test logs
      if: ${{ !success() }}
      uses: actions/upload-artifact@v3
      with:
        name: swift-ql-tests-logs-${{ runner.os }}
        path: |
          swift/ql/test/**/*.testproj/log
        retention-days: 1
